
CREATE TABLE USER_TB (
	USER_ID  VARCHAR(20) PRIMARY KEY,
	USER_NM  VARCHAR(20),
	EMAIL    VARCHAR(50),
	PASSWORD VARCHAR(20) 
);

CREATE TABLE MESSAGE_TB (
	MSG_ID    INTEGER PRIMARY KEY AUTO_INCREMENT,
	CONTENTS  VARCHAR(2000),
	WRITER_ID VARCHAR(20),
	REG_DT    TIMESTAMP 
);


CREATE TABLE UserToUser_TB (
	FROM_ID VARCHAR(20) NOT NULL,
	TO_ID   VARCHAR(20) NOT NULL
);

ALTER TABLE UserToUser_TB
	ADD CONSTRAINT PK_UserToUser_TB 
		PRIMARY KEY (
			FROM_ID,
			TO_ID
		);
