DROP TABLE IF EXISTS user_tb RESTRICT;

DROP TABLE IF EXISTS message_tb RESTRICT;

DROP TABLE IF EXISTS usertouser_tb RESTRICT;

CREATE TABLE user_tb (
	USER_ID  VARCHAR(20) PRIMARY KEY, 
	NAME     VARCHAR(20) NULL,    
	EMAIL    VARCHAR(20) NULL,     
	PASSWORD VARCHAR(20) NULL,
	IMG_TYPE VARCHAR(50) NULL,     
	IMG_FILE VARCHAR(30) NULL     
);

CREATE TABLE message_tb (
	MSG_ID   INTEGER       PRIMARY KEY AUTO_INCREMENT, 
	CONTENTS VARCHAR(2000) NULL,     
	WRITER_ID   VARCHAR(20)   NULL,
	REG_DT   TIMESTAMP     NULL
);

CREATE TABLE usertouser_tb (
	WHO  VARCHAR(20) NOT NULL, 
	WHOM VARCHAR(20) NOT NULL  
);

ALTER TABLE usertouser_tb
	ADD CONSTRAINT PK_usertouser_tb 
		PRIMARY KEY (
			WHO,  
			WHOM  
		);